default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: Emergency_Call_Support_development

test:
  <<: *default
  database: Emergency_Call_Support_test

production:
  <<: *default
  database: Emergency_Call_Support_production
  username: Emergency_Call_Support
  password: <%= ENV["EMERGENCY_CALL_SUPPORT_DATABASE_PASSWORD"] %>

  # 本番環境用のホスト設定が必要な場合、以下のように追加
  # host: <%= ENV["DATABASE_HOST"] %>